spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  applicaton:
    name: microservicecloud-config-dev
---
spring:
  profiles: test
  applicaton:
    name: microservicecloud-config-test
