spring:
  profiles:
    active: dev
---
server:
  port: 8201
spring:
  profiles: dev
  applicaton:
    name: microservicecloud-config-client
---
server:
  port: 8202
spring:
  profiles: test
  applicaton:
    name: microservicecloud-config-client
